#if !defined(__LAYOUT_DVORAK_PROGRAMMER_H_)
#define __LAYOUT_DVORAK_PROGRAMMER_H_

#include "keys.h"

const KeySpec dvorakProgrammerKeymap[] = {
/* A               =>  aA */         (KeySpec) { 0, KC_A, RShift, KC_A },
/* B               =>  xX */         (KeySpec) { 0, KC_X, RShift, KC_X },
/* C               =>  jJ */         (KeySpec) { 0, KC_J, RShift, KC_J },
/* D               =>  eE */         (KeySpec) { 0, KC_E, RShift, KC_E },
/* E               =>  .> */         (KeySpec) { 0, KC_Fullstop, RShift, KC_Fullstop },
/* F               =>  uU */         (KeySpec) { 0, KC_U, RShift, KC_U },
/* G               =>  iI */         (KeySpec) { 0, KC_I, RShift, KC_I },
/* H               =>  dD */         (KeySpec) { 0, KC_D, LShift, KC_D },
/* I               =>  cC */         (KeySpec) { 0, KC_C, LShift, KC_C },
/* J               =>  hH */         (KeySpec) { 0, KC_H, LShift, KC_H },
/* K               =>  tT */         (KeySpec) { 0, KC_T, LShift, KC_T },
/* L               =>  nN */         (KeySpec) { 0, KC_N, LShift, KC_N },
/* M               =>  mM */         (KeySpec) { 0, KC_M, LShift, KC_M },
/* N               =>  bB */         (KeySpec) { 0, KC_B, LShift, KC_B },
/* O               =>  rR */         (KeySpec) { 0, KC_R, LShift, KC_R },
/* P               =>  lL */         (KeySpec) { 0, KC_L, LShift, KC_L },
/* Q               =>  ;: */         (KeySpec) { 0, KC_Semicolon, RShift, KC_Semicolon },
/* R               =>  pP */         (KeySpec) { 0, KC_P, RShift, KC_P },
/* S               =>  oO */         (KeySpec) { 0, KC_O, RShift, KC_O },
/* T               =>  yY */         (KeySpec) { 0, KC_Y, RShift, KC_Y },
/* U               =>  gG */         (KeySpec) { 0, KC_G, LShift, KC_G },
/* V               =>  kK */         (KeySpec) { 0, KC_K, RShift, KC_K },
/* W               =>  ,< */         (KeySpec) { 0, KC_Comma, RShift, KC_Comma },
/* X               =>  qQ */         (KeySpec) { 0, KC_Q, RShift, KC_Q },
/* Y               =>  fF */         (KeySpec) { 0, KC_F, LShift, KC_F },
/* Z               =>  '" */         (KeySpec) { 0, KC_Apostrophe, RShift, KC_Apostrophe },
/* 1               =>  &% */         (KeySpec) { LShift, KC_7, RShift, KC_5 },
/* 2               =>  [7 */         (KeySpec) { 0, KC_LeftBracket, 0, KC_7 },
/* 3               =>  {5 */         (KeySpec) { LShift, KC_LeftBracket, 0, KC_5 },
/* 4               =>  }3 */         (KeySpec) { LShift, KC_RightBracket, 0, KC_3 },
/* 5               =>  (1 */         (KeySpec) { LShift, KC_9, 0, KC_1 },
/* 6               =>  =9 */         (KeySpec) { 0, KC_Equals, 0, KC_9 },
/* 7               =>  *0 */         (KeySpec) { LShift, KC_8, 0, KC_0 },
/* 8               =>  )2 */         (KeySpec) { LShift, KC_0, 0, KC_2 },
/* 9               =>  +4 */         (KeySpec) { LShift, KC_Equals, 0, KC_4 },
/* 0               =>  ]6 */         (KeySpec) { 0, KC_RightBracket, 0, KC_6 },
/* Enter           =>  Enter */      (KeySpec) { 0, KC_Enter, LShift, KC_Enter },
/* Escape          =>  Escape */     (KeySpec) { 0, KC_Escape, RShift, KC_Escape },
/* Backspace       =>  Backspace */  (KeySpec) { 0, KC_Backspace, LShift, KC_Backspace },
/* Tab             =>  Tab */        (KeySpec) { 0, KC_Tab, RShift, KC_Tab },
/* Space           =>  Space */      (KeySpec) { 0, KC_Space, LShift, KC_Space },
/* Dash            =>  !8 */         (KeySpec) { RShift, KC_1, 0, KC_8 },
/* Equals          =>  #` */         (KeySpec) { RShift, KC_3, 0, KC_Backtick },
/* LeftBracket     =>  /? */         (KeySpec) { 0, KC_ForwardSlash, LShift, KC_ForwardSlash },
/* RightBracket    =>  @^ */         (KeySpec) { RShift, KC_2, RShift, KC_6 },
/* Backslash       =>  \| */         (KeySpec) { 0, KC_Backslash, LShift, KC_Backslash },
/* International2  =>  ... */        (KeySpec) { 0, KC_International2, LShift, KC_International2 },
/* Semicolon       =>  sS */         (KeySpec) { 0, KC_S, LShift, KC_S },
/* Apostrophe      =>  -_ */         (KeySpec) { 0, KC_Dash, LShift, KC_Dash },
/* Backtick        =>  $~ */         (KeySpec) { RShift, KC_4, RShift, KC_Backtick },
/* Comma           =>  wW */         (KeySpec) { 0, KC_W, LShift, KC_W },
/* Fullstop        =>  vV */         (KeySpec) { 0, KC_V, LShift, KC_V },
/* ForwardSlash    =>  zZ */         (KeySpec) { 0, KC_Z, LShift, KC_Z },
/* CapsLock        =>  Capslock */   (KeySpec) { 0, KC_CapsLock, RShift, KC_CapsLock }
};

#endif // __LAYOUT_DVORAK_PROGRAMMER_H_
