#if !defined(__LAYOUT_QWERTY_H_)
#define __LAYOUT_QWERTY_H_

#include "keys.h"

const KeySpec qwertyKeymap[] = {
/* A               =>  aA */         (KeySpec) { 0, KC_A, RShift, KC_A },
/* B               =>  bB */         (KeySpec) { 0, KC_B, RShift, KC_B },
/* C               =>  cC */         (KeySpec) { 0, KC_C, RShift, KC_C },
/* D               =>  dD */         (KeySpec) { 0, KC_D, RShift, KC_D },
/* E               =>  eE */         (KeySpec) { 0, KC_E, RShift, KC_E },
/* F               =>  fF */         (KeySpec) { 0, KC_F, RShift, KC_F },
/* G               =>  gG */         (KeySpec) { 0, KC_G, RShift, KC_G },
/* H               =>  hH */         (KeySpec) { 0, KC_H, LShift, KC_H },
/* I               =>  iI */         (KeySpec) { 0, KC_I, LShift, KC_I },
/* J               =>  jJ */         (KeySpec) { 0, KC_J, LShift, KC_J },
/* K               =>  kK */         (KeySpec) { 0, KC_K, LShift, KC_K },
/* L               =>  lL */         (KeySpec) { 0, KC_L, LShift, KC_L },
/* M               =>  mM */         (KeySpec) { 0, KC_M, LShift, KC_M },
/* N               =>  nN */         (KeySpec) { 0, KC_N, LShift, KC_N },
/* O               =>  oO */         (KeySpec) { 0, KC_O, LShift, KC_O },
/* P               =>  pP */         (KeySpec) { 0, KC_P, LShift, KC_P },
/* Q               =>  qQ */         (KeySpec) { 0, KC_Q, RShift, KC_Q },
/* R               =>  rR */         (KeySpec) { 0, KC_R, RShift, KC_R },
/* S               =>  sS */         (KeySpec) { 0, KC_S, RShift, KC_S },
/* T               =>  tT */         (KeySpec) { 0, KC_T, RShift, KC_T },
/* U               =>  uU */         (KeySpec) { 0, KC_U, LShift, KC_U },
/* V               =>  vV */         (KeySpec) { 0, KC_V, RShift, KC_V },
/* W               =>  wW */         (KeySpec) { 0, KC_W, RShift, KC_W },
/* X               =>  xX */         (KeySpec) { 0, KC_X, RShift, KC_X },
/* Y               =>  yY */         (KeySpec) { 0, KC_Y, LShift, KC_Y },
/* Z               =>  zZ */         (KeySpec) { 0, KC_Z, RShift, KC_Z },
/* 1               =>  1! */         (KeySpec) { 0, KC_1, RShift, KC_1 },
/* 2               =>  2@ */         (KeySpec) { 0, KC_2, RShift, KC_2 },
/* 3               =>  3# */         (KeySpec) { 0, KC_3, RShift, KC_3 },
/* 4               =>  4$ */         (KeySpec) { 0, KC_4, RShift, KC_4 },
/* 5               =>  5% */         (KeySpec) { 0, KC_5, RShift, KC_5 },
/* 6               =>  6^ */         (KeySpec) { 0, KC_6, RShift, KC_6 },
/* 7               =>  7& */         (KeySpec) { 0, KC_7, LShift, KC_7 },
/* 8               =>  8* */         (KeySpec) { 0, KC_8, LShift, KC_8 },
/* 9               =>  9( */         (KeySpec) { 0, KC_9, LShift, KC_9 },
/* 0               =>  0) */         (KeySpec) { 0, KC_0, LShift, KC_0 },
/* Enter           =>  Enter */      (KeySpec) { 0, KC_Enter, LShift, KC_Enter },
/* Escape          =>  Escape */     (KeySpec) { 0, KC_Escape, RShift, KC_Escape },
/* Backspace       =>  Backspace */  (KeySpec) { 0, KC_Backspace, LShift, KC_Backspace },
/* Tab             =>  Tab */        (KeySpec) { 0, KC_Tab, RShift, KC_Tab },
/* Space           =>  Space */      (KeySpec) { 0, KC_Space, LShift, KC_Space },
/* Dash            =>  -_ */         (KeySpec) { 0, KC_Dash, LShift, KC_Dash },
/* Equals          =>  =+ */         (KeySpec) { 0, KC_Equals, LShift, KC_Equals },
/* LeftBracket     =>  [{ */         (KeySpec) { 0, KC_LeftBracket, LShift, KC_LeftBracket },
/* RightBracket    =>  ]} */         (KeySpec) { 0, KC_RightBracket, LShift, KC_RightBracket },
/* Backslash       =>  \| */         (KeySpec) { 0, KC_Backslash, LShift, KC_Backslash},
/* International2  =>  ... */        (KeySpec) { 0, KC_International2, LShift, KC_International2 },
/* Semicolon       =>  ;: */         (KeySpec) { 0, KC_Semicolon, LShift, KC_Semicolon },
/* Apostrophe      =>  '" */         (KeySpec) { 0, KC_Apostrophe, LShift, KC_Apostrophe },
/* Backtick        =>  `~ */         (KeySpec) { 0, KC_Backtick, RShift, KC_Backtick },
/* Comma           =>  ,< */         (KeySpec) { 0, KC_Comma, LShift, KC_Comma },
/* Fullstop        =>  .> */         (KeySpec) { 0, KC_Fullstop, LShift, KC_Fullstop },
/* ForwardSlash    =>  /? */         (KeySpec) { 0, KC_ForwardSlash, LShift, KC_ForwardSlash },
/* CapsLock        =>  Capslock */   (KeySpec) { 0, KC_CapsLock, LShift, KC_CapsLock }
};

#endif // __LAYOUT_QWERTY_H_
